language: android
android:
  components:
    - build-tools-23.0.1
    - android-20
jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1


before_install:
  - chmod +x gradlew
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
