language: android
android:
  components:
    - build-tools-23.0.1
    - android-20
jdk:
  - openjdk8

sudo: false

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

script:
    - ./gradlew editor-desktop:clean editor-desktop:test